# A dockerized stack for development
# execute with `docker-compose -f dev-stack.yml up`
version: '3.3'
services:
  mongodb:
    image: 'mongo:4.2'
    volumes:
      - mongo_db_data:/data/db
    ports:
      - 27017-27019:27017-27019
    networks:
      - demo
  redis:
    image: library/redis:6.0.6
    networks:
      - demo
    ports:
      - 6379:6379

volumes:
  mongo_db_data:

networks:
  demo:
